### ISSUE TITLE
Application shows black screen

### ISSUE THREAD

**Issue by HI-POT** [TronWallet/tronwallet-play-releases#2]
machine: dell xps 15, win10, x64
symptoms: the latest version of the application installed when started via desktop shortcut just black screen is visible, see screenshot below.
more details: version 12 was running fine but from time to time the same symptoms when logged in already, this is not the case in ver 14 where black screen comes up immediately when app is started.

![image](https://user-images.githubusercontent.com/44510396/71612559-88055000-2ba1-11ea-8385-7be4308c6135.png)

**Comment by pedrobertao** [comment]
@HI-POT Try a fresh download from the official link. We have fixed that problem yesterday.

**Comment by HI-POT** [comment]
Yes, just downloaded the latest ver 14 and it´s working as expected. Thx.

**Comment by SteenR** [comment]
I am still getting the black screen immediately om loading so Tronwallet 1.1.14 completely unusable for me on Linux. Kubuntu 18.04 LTS x64.
I have deleted all caches, restored wallets, still no go.
Any chance of a fix or suggestions?

**Comment by SteenR** [comment]
Sorry, I should have added. Restore works fine for the default wallet. Black screen starts happening when I try to restore my Ledger wallet.

**Comment by SteenR** [comment]
I just tried deleting cache and config folders and trying on 1.1.12 which used to work without problems and get exactly the same problem- black screen immediately on loading Ledger wallet,

**Comment by elstevega** [comment]
Edit: It loads, displays the dashboard for 3-5 seconds & then goes to a blank screen (if that helps)

Just downloaded and am seeing this same behavior.
Ubuntu 18.04 desktop
thx

**Comment by SteenR** [comment]
Interesting, I thought it was only me having this issue. Are you trying to use Ledger too?

**Comment by SteenR** [comment]
On advice from TronWallet support, I downloaded the new file- TronWalletPlay.1.1.14.AppImage- and all seems to be working well now. Big thanks to support.

**Comment by newtocrypto** [comment]
I'm having this problem too. I just downloaded the TronWalletPlay. It opened fine but as soon as my first deposit showed up the screen went blank. I closed out and opened the wallet again to the login screen. I can put in my password and it flashes for a fraction of a second to the wallet, then black screen. I tried to use my mnemonic to restore the wallet using the mobile app and it doesn't recognize that its a valid mnemonic. I also tried to use the mnemonic to restore the TronWalletPlay on my desktop and it too doesn't recognize the mnemonic.

It also says there "A new version of TronWallet Play is available for update. Would you like to proceed?" I click UPDATE and a "We will notify you as soon as the download is complete." screen pops up. I click close and nothing happens... 

What am I doing wrong?

**Comment by newtocrypto** [comment]
> On advice from TronWallet support, I downloaded the new file- TronWalletPlay.1.1.14.AppImage- and all seems to be working well now. Big thanks to support.

I downloaded that file too and I get this when I try to open it "This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page."

**Comment by SteenR** [comment]
You need to set the permissions to executable. Easiest way is- right click the Appimage, open Properties, open the Permissions tab and check the box for "Is executable".
Or better still learn how to set permissions with the command line.

**Comment by newtocrypto** [comment]
> You need to set the permissions to executable. Easiest way is- right click the Appimage, open Properties, open the Permissions tab and check the box for "Is executable".
> Or better still learn how to set permissions with the command line.

I know this will sound like I'm crazy new to computers and what you said was pretty strait forward. But.... This is what I see when I right click. I do appreciate you time and help.

![tron](https://user-images.githubusercontent.com/60119904/72769096-8559b180-3bc7-11ea-8842-72cabd2b19da.png)

**Comment by newtocrypto** [comment]
> You need to set the permissions to executable. Easiest way is- right click the Appimage, open Properties, open the Permissions tab and check the box for "Is executable".
> Or better still learn how to set permissions with the command line.

OK so I'm an idiot. Somehow I downloaded the 1.1.12.exe of the wallet... I just downloaded 1.1.14.exe and it works....

Thanks for your help...

**Comment by pedrobertao** [comment]
Closing for now since the problem seemed to be solved.
